# Menggunakan image Node.js sebagai base image
FROM node:14

# Menetapkan direktori kerja di dalam container
WORKDIR /app/mapsAPI

# Menyalin package.json dan package-lock.json ke direktori kerja
COPY package*.json ./

# Menginstal dependensi yang diperlukan
RUN npm install --production

# Menyalin seluruh kode aplikasi ke direktori kerja
COPY . .

# Menjalankan perintah build untuk aplikasi
RUN npm run build

# Menetapkan command yang akan dijalankan saat container dijalankan
CMD ["npm", "start"]
